[[module.imports]]
path = "github.com/razonyang/hb-giscus"

[[module.imports]]
path = "github.com/razonyang/hb-blog"

[params.hugopress.modules.hb-blog-comments-giscus.hooks.hb-blog-post-comments]

[params.hugopress.modules.hb-blog-comments-giscus.hooks.body-end]
