[module.hugoVersion]
extended = true

[[module.imports]]
path = "github.com/razonyang/hb-base"

[[module.imports]]
path = "github.com/razonyang/hb-heading-sign"

[params.hb.blog]
paginate = 9
post_date_format = ':date_long'

[params.hb.heading_sign.containers.".hb-blog-post-content"]
